name: "Fridaycode.net"
timezone: Europe/Sofia

permalink: /blog/:title.html

keywords: ""
description: ""

navigation:
  - title: Уеб Дизайн
    group: ["PHP", "Ruby", "Python"]

  - title: Бази Данни
    group: ["HTML", "CSS", "база 3"]


markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

pygments: true

exclude: ["Rakefile", "Rakefile.rb", "*.sublime-project", "*.sublime-workspace", "gruntfile.js", "package.json", "node_modules"]

